sudo: false

branches:
  only: 
    - master
    - APIv2-master

language: node_js

notifications:
  email:
    recipients:
      - devcenter@docusign.com
    on_success: never
    on_failure: change

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"

cache:
  directories:
    - "node_modules"
